language: rust
sudo: false
rust:
- stable
- beta
- nightly
cache: cargo
script:
- cargo build --verbose
- cargo test --verbose "${CARGO_ARGS[@]}"
matrix:
  include:
  - rust: nightly
    env: CARGO_ARGS=("--no-default-features")
