language: rust
sudo: false
rust:
- stable
- beta
- nightly
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt --vers 0.7.1
script:
- rustfmt --version
- cargo build --verbose
- cargo test --verbose "${CARGO_ARGS[@]}"
- cargo fmt --verbose -- --write-mode=diff
matrix:
  include:
  - rust: nightly
    env: CARGO_ARGS=("--no-default-features")
